# ファイル名: cloudbuild.yaml
# Artifact Registryを使用するように更新

steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/englishapp:$COMMIT_SHA', '.']

  # ビルドしたイメージを Artifact Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/englishapp:$COMMIT_SHA']

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'englishapp'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/englishapp:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_KEY=${_SUPABASE_KEY}'

# イメージのタグ付け
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/englishapp:$COMMIT_SHA'

# 代入変数
substitutions:
  _SUPABASE_URL: 'your-supabase-url'  # デフォルト値（GitHub Secretsから上書きすることを推奨）
  _SUPABASE_KEY: 'your-supabase-key'  # デフォルト値（GitHub Secretsから上書きすることを推奨）